---
title: Security
path: security
icon: mdi:shield-home
background: center / cover no-repeat url("/local/backgrounds/clear-blur.jpg")
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: entities
        title: Door Bell
        show_header_toggle: false
        entities:
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
          - sensor.ring_last_ding
          - sensor.ring_last_motion

          # - type: picture-entity
          #   title: Ring Last Video
          #   entity: camera.front_door
          #   show_info: true
          #   tap_action: dialog

  - type: entities
    title: Garage Door
    show_header_toggle: false
    entities:
      - cover.garage_door
      - sensor.garage_car_present
      - type: custom:entity-attributes-card
        filter:
          include:
            - key: cover.garage_door.wifi_signal
              name: WiFi Signal
              unit: "dBm"
            - key: cover.garage_door.distance_sensor
              name: Distance
              unit: "cm"

  - type: entities
    title: Locks
    show_header_toggle: false
    entities:
      - lock.lock_front
      - sensor.lock_front_status

  - type: entities
    title: Doors
    show_header_toggle: false
    entities:
      - entity: sensor.door_front
      - sensor.door_back
      - sensor.door_garage_entry
      - sensor.door_garage_outside

  - type: glance
    title: Occupancy
    columns: 4
    entities:
      - entity: sensor.occupancy_home
        name: Home
      - entity: sensor.occupancy_kitchen
        name: Kitchen
      - entity: sensor.occupancy_family_room
        name: Family
      - entity: sensor.occupancy_office
        name: Office
      - entity: sensor.occupancy_emma
        name: Emma
      - entity: sensor.occupancy_ethan
        name: Ethan
      - entity: sensor.occupancy_garage
        name: Garage
