---
# Rest sensor to get the base url.
#
# https://www.home-assistant.io/integrations/rest/
#
platform: rest
name: Config
resource: http://localhost:8123/api/config
headers:
  Authorization: !secret ha_api_key
value_template: 'OK'
json_attributes:
  - 'external_url'
  - 'internal_url'
