---
language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant pyyaml flake8 yamllint
before_script:
  - hass --version
  - yamllint --version
script:
  - yamllint $(git ls-files '*.yaml' '*.yml' '*.yaml.disabled')
  - mv travis_secrets.yaml secrets.yaml
  - hass -c . --script check_config
