light.living_room_level:
  ignored: false
  polling_intensity: 1
  refresh_value: 2
  delay: 3
light.kitchen_level:
  ignored: false
  polling_intensity: 1
  refresh_value: 2
  delay: 3
light.family_room_level:
  ignored: false
  polling_intensity: 1
  refresh_value: 2
  delay: 3
light.play_space_level:
  ignored: false
  polling_intensity: 1
  refresh_value: 2
  delay: 3
switch.front_entry_light_switch:
  ignored: false
  polling_intensity: 1
switch.outside_front_light_switch:
  ignored: false
  polling_intensity: 1
switch.garage_entry_light_switch:
  ignored: false
  polling_intensity: 1
switch.dining_room_light_switch:
  ignored: false
  polling_intensity: 1
switch.hallway_light_switch:
  ignored: false
  polling_intensity: 1
lock.lock_front_locked:
  ignored: false
  polling_intensity: 2
