###########################################################
# Group: Automation
###########################################################

automation:
  name: Automation
  entities:
  - automation.front_lights_on_at_night
  - automation.front_lights_off_at_night
  # - automation.harmony_bedroom_activity
  # - automation.harmony_bedroom_off
  # - automation.harmony_living_room_activity
  # - automation.harmony_living_room_off
  - automation.shield_bedroom_auto_off
  - automation.shield_living_room_playing_at_night
  - automation.shield_living_room_paused_at_night
  - automation.lights_on_arrive_home
  - automation.lights_off_leave_home
  - automation.notify_disk_space_at_90
  - automation.notify_mail_delivery
  - automation.notify_packages_delivered
  - automation.notify_packages_out_for_delivery
  - automation.notify_sensor_low_battery
  - automation.notify_update_available
  - automation.zwave_heal_230am
